sources:
  hr_events:
    format: csv
    landing_relpath: "hr_events/hr_events.csv"
    keys: ["employee_id", "event_ts", "event_type"]
  headcount_snapshots:
    format: csv
    landing_relpath: "headcount/headcount_snapshots.csv"
    keys: ["snapshot_date", "employee_id"]
  org:
    format: csv
    landing_relpath: "org/org.csv"
    keys: ["org_id"]
